### ISSUE TITLE
<Environment preset="studio" />, Environment Component throws an error.

### ISSUE THREAD

**Issue by Jass2k23** [a-trost/creative-portfolio#5]
Error: Could not load studio_small_03_1k.hdr: Failed to fetch

![Screenshot 2024-07-05 at 12 10 54 PM](https://github.com/a-trost/creative-portfolio/assets/94312817/3dc469ac-8950-4060-9cac-5e3056e37c6d)

App runs properly after commenting Environment component.

**Comment by a-trost** [comment]
Hey Jass,

The quickest way would be to share your project with me so that I can  see what's going on.

**Comment by Jass2k23** [comment]
Here's the link: https://github.com/Jass2k23/My-Portfolio
I even forked your project, but the error still remains.

**Comment by a-trost** [comment]
Hey @Jass2k23 , your repo is private so I can't access it.

**Comment by Jass2k23** [comment]
Oh sorry!
I've made it public.

**Comment by Jass2k23** [comment]
<img width="1680" alt="Screenshot 2024-07-08 at 6 40 56 PM" src="https://github.com/a-trost/creative-portfolio/assets/94312817/2d5ac236-a533-410c-b2b9-a5f95ff722c1">
Even your deployed website is throwing the same error.
I think it's something to do with drei library.

**Comment by a-trost** [comment]
I'm not getting that in mine, even on a Guest chrome profile. 
<img width="1919" alt="image" src="https://github.com/a-trost/creative-portfolio/assets/19617280/b8e94674-5f10-4e27-b8ad-286d650ec5c1">

Can you try opening the page on a guest profile so that you're not bringing in any chrome extensions that might be causing the problem? 

I get the same result in Safari and on my phone.
<img width="1507" alt="image" src="https://github.com/a-trost/creative-portfolio/assets/19617280/566c96e2-cc3d-41ab-bbad-ff127a7c1f91">

I think you have some kind of extension or vpn or something else going on here.

**Comment by Jass2k23** [comment]
Yep, the extension "Allow CORS" was causing this.
Thanks, Alex.
and thank you for contributing in the community through your tutorials.
Your YouTube content is great!!
